### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by dnanhkhoa** [dnanhkhoa/bert-span-parser#2]
Hello @ptpuyen1511 

Could you please help me to put some of your previous results into ReadMe?

**Comment by ptpuyen1511** [comment]
Hi @dnanhkhoa 

I just finished it. If you have any further requests, please let me know.

**Comment by dnanhkhoa** [comment]
Hi @ptpuyen1511 

You are really fast, thank you so much!!
The results look fine to me but I am thinking about adding several baseline results for comparison. How do you think?

**Comment by ptpuyen1511** [comment]
Great idea. I have just added some empirical results on the baseline model as well as other research.

**Comment by ptpuyen1511** [comment]
Hi @dnanhkhoa

That is great idea 😉. I have just added some empirical results on the baseline model as well as other research.

**Comment by dnanhkhoa** [comment]
Hi @ptpuyen1511,

Nice, thank you for the update. I think it's better to cite to your paper. Do you mind to update again 😂

**Comment by ptpuyen1511** [comment]
No, not at all 😁 Actually, if you did not ask, I will also add citation today.
I have updated again 😂

**Comment by dnanhkhoa** [comment]
Ah, sorry I wasn't clear, I mean your paper :D

**Comment by dnanhkhoa** [comment]
Anw, thank you so much for your help :+1:

**Comment by ptpuyen1511** [comment]
> Ah, sorry I wasn't clear, I mean your paper :D

No no, it's my fault. I read the comments last night so I was confused 😂

Updated again 🤣

**Comment by dnanhkhoa** [comment]
Nice, thank you, I will close this issue to mark as done :D
